# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pholo', '0002_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='store',
        ),
        migrations.AddField(
            model_name='table',
            name='store',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='pholo.Store'),
        ),
    ]
